### ISSUE TITLE
Account 의 버튼 색깔이 무엇이 좋을까요? (사진에 있는 회색 혹은 파랑)

### ISSUE THREAD

**Issue by 1317Stephen** [sejnii/softengineering_yeeunsejinhyeji#10]
![account_main_btn_color](https://user-images.githubusercontent.com/33503422/33161800-3c840a08-d069-11e7-9b64-561fb1cc9080.png)
![image](https://user-images.githubusercontent.com/33503422/33162327-6bc5deec-d06c-11e7-8037-c3ca7a87efd3.png)

**Comment by sejnii** [comment]
저는 회색이 깔끔하고 예쁜 것 같아요:)

**Comment by 1317Stephen** [comment]
감사합니다 👍
